---
- name: test book
  hosts: host 
  become: true
  tasks:
        - name: Install HTTPD        
          dnf:
                    name: httpd
                    state: present
                    update_cache: yes
        - name: run 
          service:
                    name: httpd
                    state: started
                    enabled: yes
        - debug:
            var: ansible_facts["uptime_seconds"]
            verbosity: 1

        - name: Restart Apache if uptime exceeds 24 hours
          service:
            name: httpd
            state: restarted
          when: ansible_facts["uptime_seconds"] | int > 600               
